### PR TITLE
Fix for: Framing does not respect specified value #300

### LINKED ISSUE #300: Framing does not respect specified value
**Expected Behaviour**: Given a document with 2 persons "Jane" and "John" and a frame for `"givenName": "John"` I expect the result to contain only John, but not Jane.

**Actual Behaviour**: The result contains both persons, just that Janes givenName is set to `null`

I have set up the [exact scenario in the playground here](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40vocab%22%3A%22https%3A%2F%2Fschema.org%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%221%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22John%20Doe%22%2C%22givenName%22%3A%22John%22%2C%22familyName%22%3A%22Doe%22%7D%2C%7B%22%40id%22%3A%222%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22Jane%20Doe%22%2C%22givenName%22%3A%22Jane%22%7D%5D%7D&frame=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40vocab%22%3A%22https%3A%2F%2Fschema.org%2F%22%7D%2C%22givenName%22%3A%22John%22%7D).

The expected result there would be:

```
{
  "@context": {
    "@version": 1.1,
    "@vocab": "https://schema.org/"
  },
  "@id": "1",
  "@type": "Person",
  "name": "John Doe",
  "givenName": "John",
  "familyName": "Doe"
}
```

**Affected versions**
- jsonld playground as  of 2019-03-04
- jsonld npm package version 1.5.4
- works *as expected* in the [RDF Distiller](http://rdf.greggkellogg.net/distiller?command=serialize)

### PR DESCRIPTION
**Pull request by michaelcpuckett**
This fixes #300 to match behavior in RDF Distiller.

> Expected Behaviour: Given a document with 2 persons "Jane" and "John" and a frame for "givenName": "John" I expect the result to contain only John, but not Jane.

> Actual Behaviour: The result contains both persons, just that Janes givenName is set to null

This moves the initial check on the node to see if it has any properties so that value matches can be checked.

I added a test based on the issue.

(Originally opened #373 but spotted an issue after checking the test-suites -- Now all tests are passing locally.)

### CODE REVIEW

**Comment by michaelcpuckett** [comment]
This is passing the new test, but a more complicated test is failing locally. I'll leave this open while I look further.

**Comment by davidlehn** [comment]
A test like this should be added to the main test suite too.

**Comment by michaelcpuckett** [comment]
OK, it's working now.

I moved the 3 tests to here:

https://github.com/w3c/json-ld-framing/pull/100

I emailed the group regarding adding the tests.

File: lib/frame.js [hunk 1]
```diff
@@ -596,35 +596,30 @@ function _filterSubject(state, subject, frame, flags) {
...
       } else {
-        if(graphTypes.isValue(thisFrame)) {
-          // match on any matching value
-          matchThis = nodeValues.some(nv => _valueMatch(thisFrame, nv));
-        } else if(graphTypes.isSubject(thisFrame) ||
-          graphTypes.isSubjectReference(thisFrame)) {
-          matchThis =
-            nodeValues.some(nv => _nodeMatch(state, thisFrame, nv, flags));
-        } else if(graphTypes.isList(thisFrame)) {
+        if (graphTypes.isList(thisFrame)) {
```
Comment (davidlehn) [inline lib/frame.js]: Please run "npm run lint".  Style we use omits space after `if`.

Comment (michaelcpuckett) [reply lib/frame.js]: OK, should be resolved now.

**Comment by gkellogg** [comment]
You can remove the following lines from test-common:

```
        /frame-manifest.jsonld#tin01$/,
        /frame-manifest.jsonld#tin02$/,
```

This still leaves 2 list tests and one included test, which might have a related fix.

**Comment by gkellogg** [comment]
It ended up that tin03 was failing because framing was order dependent. I updated the test to simplify, so tin03 passes too and the following can be removed from test-common.js:

```
        // included
        /frame-manifest.jsonld#tin01$/,
        /frame-manifest.jsonld#tin02$/,
        /frame-manifest.jsonld#tin03$/,
```

**Comment by davidlehn** [comment]
Thanks!
